# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "Ubuntu precise 64 VMWare"
    config.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"
    config.vm.network :forwarded_port, guest: 9200, host: 9200
    config.vm.provision :puppet do |puppet|
    	puppet.module_path = '../setup/modules'
    	puppet.manifests_path = '../setup/manifests'
    	puppet.manifest_file = 'default.pp'
    	puppet.options = '--verbose --debug'
  	end


    #config.vm.provision "shell", inline: "sudo apt-get update -y"
    #config.vm.provision "shell", inline: "sudo apt-get install -y curl"
    #config.vm.provision "shell", inline: "sudo apt-get install openjdk-7-jre-headless -y"
    #config.vm.provision "shell", inline: "sudo wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.0.deb"
    #config.vm.provision "shell", inline: "sudo dpkg -i elasticsearch-0.90.0.deb"
    #config.vm.provision "shell", inline: "sudo service elasticsearch start"
end